### ISSUE TITLE
Notas sobre flujo

### ISSUE THREAD

**Issue by danielcasadociencias** [aldazosa/taller-clojure#9]
Redactar notas, ejemplos y ejercicio sobre flujo:

- If
- when
- Cond
- loop/recur
 -Otros: case y condp

**Comment by danielcasadociencias** [comment]
Ya se subió a `9-flujo` las nota de estos temas.

Revisé `condp` y creo que se me hace un poco complicada para el alcance de este curso y no escencial para empezar a escribir clojure; así que no la incluí.

@aldazosa , @dianamontes1516 ¿cómo las ven?

**Comment by aldazosa** [comment]
Se ve bien :thumbsup:, van algunas observaciones:

Hay que revisar que truthy/falsey no se esté encimando con la parte de booleanos que estaba haciendo @dianamontes1516.

Para que se acostumbren a la forma en la que pueden ingresar respuestas en 4clojure (sin `def` o `defn`, igual sería mejor ejempllicar la suma con una función dentro de un `let`. Algo como:

```clj
(defn suma-todos
  [coll]
  (let [ayudante (fn [acc coll] ;; Ayuda para usar recursión de cola
                  ,,,)]
    (ayudante 0 coll)))
```

No estoy seguro de como el ejercicio de `mi-map` cae bien aquí, pareciera más adecuado para la sección de transformaciones.

Para el `cond`, hay que mencionar que `:else` es convención y no sintaxis.

**Comment by aldazosa** [comment]
Algo más, creo que no tenemos `for` en ningún lado. Podríamos ponerlo aquí (mencionando que es una construcción distinta al `for` en otros lenguajes) o tal vez en colecciones. ¿Qué opinas?

**Comment by danielcasadociencias** [comment]
> Hay que revisar que truthy/falsey no se esté encimando con la parte de booleanos que estaba haciendo @dianamontes1516.

Ah no me percaté que se cubría antes. Lo remuevo entonces.

> Para que se acostumbren a la forma en la que pueden ingresar respuestas en 4clojure (sin def o defn, igual sería mejor ejempllicar la suma con una función dentro de un let. Algo como:
> 
> ```clojure
> (defn suma-todos
>   [coll]
>   (let [ayudante (fn [acc coll] ;; Ayuda para usar recursión de cola
>                   ,,,)]
>     (ayudante 0 coll)))
> ```

Ese ejemplo lo usé para ejemplificar que, si usas `recur` dentro del cuerpo de una función con nombre, no debes de amarrar los parámetros con un `loop` antes. Por eso le puse nombre a la función que se usa para recursión de cola. ¿Quizá el docstring de _"Esta función es necesaria para construir recursión de cola"_ es el que sobra?

> No estoy seguro de como el ejercicio de mi-map cae bien aquí, pareciera más adecuado para la sección de transformaciones.

Lo añadí porque se soluciona con `loop` y `recur`. Pero igual puedo buscar otro.

> Para el cond, hay que mencionar que :else es convención y no sintaxis.

Ah va. Tiene sentido. Lo cambié

**Comment by aldazosa** [comment]
> Ese ejemplo lo usé para ejemplificar que, si usas `recur` dentro del cuerpo de una función con nombre, no debes de amarrar los parámetros con un `loop` antes. Por eso le puse nombre a la función que se usa para recursión de cola. ¿Quizá el docstring de _"Esta función es necesaria para construir recursión de cola"_ es el que sobra?
> 
> >



> > Para que se acostumbren a la forma en la que pueden ingresar respuestas en 4clojure (sin def o defn, igual sería mejor ejempllicar la suma con una función dentro de un let. Algo como:
> > ```clojure
> > (defn suma-todos
> >   [coll]
> >   (let [ayudante (fn [acc coll] ;; Ayuda para usar recursión de cola
> >                   ,,,)]
> >     (ayudante 0 coll)))
> > ```
> 
> Ese ejemplo lo usé para ejemplificar que, si usas `recur` dentro del cuerpo de una función con nombre, no debes de amarrar los parámetros con un `loop` antes. Por eso le puse nombre a la función que se usa para recursión de cola. ¿Quizá el docstring de _"Esta función es necesaria para construir recursión de cola"_ es el que sobra?
> 

Sí, eso está bien (que necesites uses una función con acumulador para mostrar el loop/recur). Lo que decía es que se haga sin defn. Si quieres ponerle nombre a la función para tener el ancla del loop, igual se puede hacer con `fn` :smile:. Algo como:

```clj
(defn suma-todos
  [enteros]
  (let [suma (fn suma [acc enteros]
               (if (empty? enteros)
                 acc
                 (recur
                   (+ acc (first enteros))
                   (rest enteros))))]
    (suma 0 enteros)))
```
También se puede usar `letfn`:

```clj
(defn suma-todos
  [enteros]
  (letfn [(suma [acc enteros]
            (if (empty? enteros)
              acc
              (recur
                (+ acc (first enteros))
                (rest enteros))))]
    (suma 0 enteros)))
```

> > No estoy seguro de como el ejercicio de mi-map cae bien aquí, pareciera más adecuado para la sección de transformaciones.
> 
> Lo añadí porque se soluciona con `loop` y `recur`. Pero igual puedo buscar otro.

Igual algo que con una implementación normal se acabe el stack y que funcione bien con loop/recur (que sería el caso principal que resolverían con esa herramienta).

**Comment by danielcasadociencias** [comment]
> Si quieres ponerle nombre a la función para tener el ancla del loop, igual se puede hacer con fn smile.

Ah claro. Lo corregí

> Igual algo que con una implementación normal se acabe el stack y que funcione bien con loop/recur (que sería el caso principal que resolverían con esa herramienta).

Cambié el ejercicio a calcular en n-ésimo número de Fibonacci, que si no se hace con `recur` se acaba el stack.

También hice rebase con `master`.

**Comment by danielcasadociencias** [comment]
Se agrega `doseq` y se cambia el ejercicio de fibonaccio por implementar factorial
